// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnlBE8WHSaMfF7j8tHjfscO90VlXctRA',
    appId: '1:129802333962:web:adddccb551976df95c94f3',
    messagingSenderId: '129802333962',
    projectId: 'paleblue-tech',
    authDomain: 'paleblue-tech.firebaseapp.com',
    storageBucket: 'paleblue-tech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cnopgFhWdZYM04CA6pCt-hYozkZYOXQ',
    appId: '1:129802333962:android:52cb230be15b56b45c94f3',
    messagingSenderId: '129802333962',
    projectId: 'paleblue-tech',
    storageBucket: 'paleblue-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcfgG1U2ddc9nQ9kbGX2eTQ2wUp_ggnk',
    appId: '1:129802333962:ios:d7a006ab352960225c94f3',
    messagingSenderId: '129802333962',
    projectId: 'paleblue-tech',
    storageBucket: 'paleblue-tech.appspot.com',
    iosClientId: '129802333962-nd9e35s5t5u3sdp0e8cpb717r31ot2k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.paleblueTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcfgG1U2ddc9nQ9kbGX2eTQ2wUp_ggnk',
    appId: '1:129802333962:ios:12a6f09fdf8eb1da5c94f3',
    messagingSenderId: '129802333962',
    projectId: 'paleblue-tech',
    storageBucket: 'paleblue-tech.appspot.com',
    iosClientId: '129802333962-7g9ddalpbaleko0jvck440b81d1p9dmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.paleblueTech.RunnerTests',
  );
}
